namespace MatSplit.Web.Ui;

/// <summary>
/// A group shown in the left menu. Sub entries (expenses, payments, balance,
/// history, members) are generated by the menu partial from <see cref="Id"/>.
/// </summary>
/// <param name="Id">Group id, used for the ?groupId= query parameter.</param>
/// <param name="Name">Display name.</param>
/// <param name="IsGroupAdmin">True when the current user administers the group.</param>
public sealed record MenuGroupEntry(long Id, string Name, bool IsGroupAdmin = false);
